"""empty message

Revision ID: 9a660aeef662
Revises: fe49ba9c5fcc
Create Date: 2026-03-04 22:04:13.699245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a660aeef662'
down_revision = 'fe49ba9c5fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=128), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('tracking_number'))

    op.drop_table('shipments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tracking_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('origin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('destination', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('tracking_number'), ['tracking_number'], unique=True)

    op.drop_table('shipment')
    # ### end Alembic commands ###
